### ISSUE TITLE
Is it a good idea to have fragments defined in a separate file, like schema?

### ISSUE THREAD

**Issue by choonkeat** [harmboschloo/graphql-to-elm#14]
I have various queries/mutations that inevitably have the same selection set that ideally i'd like to only specify once, as a fragment

``` graphql
# ThingByID.gql
query ($thingID: ID!) {
    thingByID(id: $thingID) {
        ...thingFields
    }
}
```

``` graphql
# CreateThing.gql
mutation ($input: CreateThingInput!) {
    createThing(input: $input) {
        ...thingFields
    }
}
```

``` graphql
# UpdateThingByID.gql
mutation ($id: ID!, $input: UpdateThingInput!) {
    updateThingByID(id: $id, input: $input) {
        ...thingFields
    }
}
```

Might have missed the mechanism to do so, but it seems like I need to define the same fragment inside each of the above `.gql` file. Can we have a standalone file instead, e.g.

``` graphql
# fragments.gql
fragment thingFields on Thing {
    name
    description
}
```

that `graphqlToElm` function would auto-append the content of fragments.sql to each query's gql file, prior to doing the parsing?

``` diff
    graphqlToElm({
      schema: "./src/schema.gql",
+     fragments: "./src/fragments.gql",
      queries: ["./src/Queries/Messages.gql"],
```

it's a bit more complicated than just appending, i think, since unused fragment currently throws `Unhandled promise rejection` (haven't dug deeper)

**Comment by harmboschloo** [comment]
Having fragments in separate files sounds useful. But I feel it's not really a problem of `graphql-to-elm`. Another option would be to concat the necessary files before giving them to `graphql-to-elm`. 

You just have to write them to a temporary location. But what we could do it to allow `queries` to be specified as strings (next to filenames), then you wouldn't need the file write.

**Comment by choonkeat** [comment]
> concat the necessary files before giving them to graphql-to-elm
> write them to a temporary location

true. i think i'll do just that 🙇
