### ISSUE TITLE
Optional.Absent is sending in `null`

### ISSUE THREAD

**Issue by peteygao** [harmboschloo/graphql-to-elm#27]
What the subject says. I believe that, instead, it should be omitting the parameter entirely in the mutation query. This is leading to data being silently overwritten in the DB when that parameter should be ignored.

**Comment by harmboschloo** [comment]
Hi. That is unfortunate! I had a quick look and I don't really see a problem on the graphql-to-elm side. In the code [here](https://github.com/harmboschloo/graphql-to-elm/blob/master/src/GraphQL/Optional.elm#L97) it doesn't encode an `Absent` value. I also checked in the browser dev tools with my application and `Absent` values are omitted as they should be.

Maybe you could check in your browser's dev tools what variables are actually send to the server? In Chrome open the dev tools (F12), then make the graphql request. Then in the Network tab select the graphql request, click the Headers tab and scroll all the way to the bottom. There you should see the variables send by the frontend under Request Payload.

**Comment by peteygao** [comment]
Sorry for the late reply, but you're likely correct. I haven't touched this code base in a long time but I imagine the error was in our codebase somehow since my vague memory was that we managed to resolve the issue 😅.
